# frozen_string_literal: true
source "https://rubygems.org"

group :development, :test do
  gem "rake"
  gem "pry" # Easily debug from your console with `binding.pry`
  gem "pry-byebug", platform: :mri # Step-by-step debugging

  gem "cancancan"
  gem "pundit", ">= 2.2.0"
  gem "jruby-openssl", platform: :jruby

  gem "draper", ">= 4.0.4"
  gem "devise", ">= 4.8.1"

  gem "rails", "~> 7.1.0"
  gem "activerecord-jdbcsqlite3-adapter", platform: :jruby

  gem "sprockets-rails", ">= 3.3.0"
  gem "sassc-rails"
end

group :test do
  gem "cuprite", ">= 0.14"
  gem "capybara", ">= 3.36.0"
  gem "webrick", ">= 1.8.2"
  gem "db-query-matchers", ">= 0.11.0"

  gem "simplecov", require: false # Test coverage generator. Go to /coverage/ after running tests
  gem "cucumber-rails", ">= 3.0.0", require: false
  gem "cucumber"
  gem "database_cleaner", ">= 2.0.2"
  gem "jasmine", ">= 3.0.0"
  gem "jasmine-core"
  gem "launchy"
  gem "parallel_tests"
  gem "rails-i18n" , ">= 7.0.1" # Provides default i18n for many languages
  gem "rspec-rails", ">= 5.0.3"
  gem "sqlite3", platform: :mri
end

gemspec path: "../.."
