# frozen_string_literal: true
source "https://rubygems.org"

group :development, :test do
  gem "rake"
  gem "pry" # Easily debug from your console with `binding.pry`
  gem "pry-byebug", platform: :mri # Step-by-step debugging

  gem "cancancan"
  gem "pundit", ">= 2.2.0"
  gem "jruby-openssl", platform: :jruby

  gem "draper"
  gem "devise", ">= 4.8.1"

  gem "rails", "~> 6.1.7", ">= 6.1.7.5"
  gem "activerecord-jdbcsqlite3-adapter", ">= 61.0", platform: :jruby

  gem "sprockets-rails", ">= 3.3.0"
  gem "sassc-rails"
end

group :test do
  gem "cuprite"
  gem "capybara"
  gem "webrick"
  gem "db-query-matchers", ">= 0.11.0"

  gem "simplecov", require: false # Test coverage generator. Go to /coverage/ after running tests
  gem "cucumber-rails", ">= 2.5.0", require: false
  gem "cucumber"
  gem "database_cleaner", ">= 2.0.2"
  gem "jasmine"
  gem "jasmine-core"
  gem "launchy"
  gem "parallel_tests"
  gem "rails-i18n" , ">= 6.0.0" # Provides default i18n for many languages
  gem "rspec-rails", ">= 5.0.3"
  gem "sqlite3", platform: :mri
end

gemspec path: "../.."
